name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 80.78.240.29 >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          ssh root@80.78.240.29 << 'EOF'
          export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load nvm
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/nvm/versions/node/v18/bin
            cd /var/www/mpstats.space
            git pull origin main

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Restart the application using PM2
            pm2 restart Mpstats
          EOF
