name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 80.78.240.29 >> ~/.ssh/known_hosts

      - name: Deploy to Server via SSH
        run: |
          ssh user@80.78.240.29 << 'EOF'
            cd /var/www/api.mpstats.space
            git pull origin main

            # Install dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader

            # Run migrations
            php artisan migrate --force

            # Clear and cache configurations
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Restart PHP-FPM (ensure the user has permissions)
            sudo systemctl restart php8.2-fpm
          EOF